[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "backend"
source = "./backend"
variables = { NODE_ENV = "production", PORT = "$PORT" }

[services.build]
buildCommand = "npm ci && npm run build"
startCommand = "npm start"

[[services]]
name = "frontend" 
source = "./frontend"
variables = { NODE_ENV = "production", REACT_APP_API_URL = "${{backend.RAILWAY_PUBLIC_DOMAIN}}" }

[services.build]
buildCommand = "npm ci && npm run build"
startCommand = "npm run serve"

[[services]]
name = "ml-pipeline"
source = "./ml"
variables = { PYTHON_ENV = "production" }

[services.build]
buildCommand = "pip install -r requirements.txt"
startCommand = "python src/enterprise_ml_pipeline.py"

[[services]]
name = "etl-pipeline"
source = "./etl"
variables = { PYTHON_ENV = "production" }

[services.build]
buildCommand = "pip install -r requirements.txt"
startCommand = "python run_pipeline.py --mode batch"